In [2]:
import pandas as pd
import os
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

In [3]:
constructors = pd.read_csv("../data/constructors.csv")

In [4]:
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team

In [5]:
for x in constructors["nationality"].unique().tolist():
    print(x)

British
German
French
Italian
Japanese
Austrian
Indian
Dutch
Russian
Swiss
Irish
Hong Kong
Brazilian
Canadian
Mexican
American
Australian
New Zealander
South African
Rhodesian
Belgian
East German
Spanish
Malaysian

In [6]:
nationality_to_country = {
    'British': 'United Kingdom',
    'German': 'Germany',
    'French': 'France',
    'Italian': 'Italy',
    'Japanese': 'Japan',
    'Austrian': 'Austria',
    'Indian': 'India',
    'Dutch': 'Netherlands',
    'Russian': 'Russia',
    'Swiss': 'Switzerland',
    'Irish': 'Ireland',
    'Hong Kong': 'Hong Kong',  # Special Administrative Region of China
    'Brazilian': 'Brazil',
    'Canadian': 'Canada',
    'Mexican': 'Mexico',
    'American': 'United States',
    'Australian': 'Australia',
    'New Zealander': 'New Zealand',
    'South African': 'South Africa',
    'Rhodesian': 'Zimbabwe',  # Rhodesia is the former name of Zimbabwe
    'Belgian': 'Belgium',
    'East German': 'Germany',  # East Germany unified with West Germany to form Germany
    'Spanish': 'Spain',
    'Malaysian': 'Malaysia'
}

In [7]:
constructors["country"] = constructors["nationality"].map(nationality_to_country)
constructors["country"].value_counts()

United Kingdom    86
United States     39
Italy             29
France            13
Germany           11
Japan              5
Switzerland        5
South Africa       3
Netherlands        3
Canada             2
Malaysia           2
Russia             2
Ireland            1
Brazil             1
Mexico             1
India              1
Australia          1
New Zealand        1
Austria            1
Zimbabwe           1
Belgium            1
Spain              1
Hong Kong          1
Name: country, dtype: int64

In [8]:
iso_alpha_codes = {
    'United Kingdom': 'GBR',
    'Germany': 'DEU',
    'France': 'FRA',
    'Italy': 'ITA',
    'Japan': 'JPN',
    'Austria': 'AUT',
    'India': 'IND',
    'Netherlands': 'NLD',
    'Russia': 'RUS',  # No code found, possibly due to a mismatch in the country name
    'Switzerland': 'CHE',
    'Ireland': 'IRL',
    'Hong Kong': 'HKG',  # Special Administrative Region of China
    'Brazil': 'BRA',
    'Canada': 'CAN',
    'Mexico': 'MEX',
    'United States': 'USA',
    'Australia': 'AUS',
    'New Zealand': 'NZL',
    'South Africa': 'ZAF',
    'Zimbabwe': 'ZWE',
    'Belgium': 'BEL',
    'Spain': 'ESP',
    'Malaysia': 'MYS'
}

In [9]:
constructors["iso_alpha"] = constructors["country"].map(iso_alpha_codes)
constructors["iso_alpha"].value_counts()

GBR    86
USA    39
ITA    29
FRA    13
DEU    11
JPN     5
CHE     5
ZAF     3
NLD     3
CAN     2
MYS     2
RUS     2
IRL     1
BRA     1
MEX     1
IND     1
AUS     1
NZL     1
AUT     1
ZWE     1
BEL     1
ESP     1
HKG     1
Name: iso_alpha, dtype: int64

In [10]:
country_to_continent = {
    'United Kingdom': 'Europe',
    'Germany': 'Europe',
    'France': 'Europe',
    'Italy': 'Europe',
    'Japan': 'Asia',
    'Austria': 'Europe',
    'India': 'Asia',
    'Netherlands': 'Europe',
    'Russia': 'Europe',  # Geographically in both Europe and Asia, commonly associated with Europe
    'Switzerland': 'Europe',
    'Ireland': 'Europe',
    'Hong Kong': 'Asia',  # Special Administrative Region of China
    'Brazil': 'South America',
    'Canada': 'North America',
    'Mexico': 'North America',
    'United States': 'North America',
    'Australia': 'Oceania',
    'New Zealand': 'Oceania',
    'South Africa': 'Africa',
    'Zimbabwe': 'Africa',
    'Belgium': 'Europe',
    'Spain': 'Europe',
    'Malaysia': 'Asia'
}

In [11]:
constructors["continent"] = constructors["country"].map(country_to_continent)
constructors["continent"].value_counts()

Europe           153
North America     42
Asia               9
Africa             4
Oceania            2
South America      1
Name: continent, dtype: int64

In [14]:
for x in constructors["country"].unique():
    print(x)

United Kingdom
Germany
France
Italy
Japan
Austria
India
Netherlands
Russia
Switzerland
Ireland
Hong Kong
Brazil
Canada
Mexico
United States
Australia
New Zealand
South Africa
Zimbabwe
Belgium
Spain
Malaysia

In [15]:
country_to_flag = {'United Kingdom': 'ðŸ‡¬ðŸ‡§',
 'Germany': 'ðŸ‡©ðŸ‡ª',
 'France': 'ðŸ‡«ðŸ‡·',
 'Italy': 'ðŸ‡®ðŸ‡¹',
 'Japan': 'ðŸ‡¯ðŸ‡µ',
 'Austria': 'ðŸ‡¦ðŸ‡¹',
 'India': 'ðŸ‡®ðŸ‡³',
 'Netherlands': 'ðŸ‡³ðŸ‡±',
 'Russia': 'ðŸ‡·ðŸ‡º',
 'Switzerland': 'ðŸ‡¨ðŸ‡­',
 'Ireland': 'ðŸ‡®ðŸ‡ª',
 'Hong Kong': 'ðŸ‡­ðŸ‡°',
 'Brazil': 'ðŸ‡§ðŸ‡·',
 'Canada': 'ðŸ‡¨ðŸ‡¦',
 'Mexico': 'ðŸ‡²ðŸ‡½',
 'United States': 'ðŸ‡ºðŸ‡¸',
 'Australia': 'ðŸ‡¦ðŸ‡º',
 'New Zealand': 'ðŸ‡³ðŸ‡¿',
 'South Africa': 'ðŸ‡¿ðŸ‡¦',
 'Zimbabwe': 'ðŸ‡¿ðŸ‡¼',
 'Belgium': 'ðŸ‡§ðŸ‡ª',
 'Spain': 'ðŸ‡ªðŸ‡¸',
 'Malaysia': 'ðŸ‡²ðŸ‡¾'}

In [16]:
constructors["country_flag"] = constructors["country"].map(country_to_flag)
constructors["country_flag"].value_counts()

ðŸ‡¬ðŸ‡§    86
ðŸ‡ºðŸ‡¸    39
ðŸ‡®ðŸ‡¹    29
ðŸ‡«ðŸ‡·    13
ðŸ‡©ðŸ‡ª    11
ðŸ‡¯ðŸ‡µ     5
ðŸ‡¨ðŸ‡­     5
ðŸ‡¿ðŸ‡¦     3
ðŸ‡³ðŸ‡±     3
ðŸ‡¨ðŸ‡¦     2
ðŸ‡²ðŸ‡¾     2
ðŸ‡·ðŸ‡º     2
ðŸ‡®ðŸ‡ª     1
ðŸ‡§ðŸ‡·     1
ðŸ‡²ðŸ‡½     1
ðŸ‡®ðŸ‡³     1
ðŸ‡¦ðŸ‡º     1
ðŸ‡³ðŸ‡¿     1
ðŸ‡¦ðŸ‡¹     1
ðŸ‡¿ðŸ‡¼     1
ðŸ‡§ðŸ‡ª     1
ðŸ‡ªðŸ‡¸     1
ðŸ‡­ðŸ‡°     1
Name: country_flag, dtype: int64

In [17]:
constructors.to_pickle("../data/constructors.pkl")

In [18]:
constructors.head()

,constructorId,constructorRef,name,nationality,url,country,iso_alpha,continent,country_flag
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,United Kingdom,GBR,Europe,ðŸ‡¬ðŸ‡§
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber,Germany,DEU,Europe,ðŸ‡©ðŸ‡ª
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,United Kingdom,GBR,Europe,ðŸ‡¬ðŸ‡§
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...,France,FRA,Europe,ðŸ‡«ðŸ‡·
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso,Italy,ITA,Europe,ðŸ‡®ðŸ‡¹